version: "3.0"

services:
  api:
    container_name: "api"
    volumes:
      - ./:/workspace
      - ~/.aws/:/root/.aws:ro
    build: .
    ports:
      - 8080:8080
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8080